//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanShare.App.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PlanShare.App.Resources.ResourceTexts", typeof(ResourceTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LOGIN_WITH_EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_WITH_EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        public static string SUBTITLE_REGISTER_ACCOUNT {
            get {
                return ResourceManager.GetString("SUBTITLE_REGISTER_ACCOUNT", resourceCulture);
            }
        }
        
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        public static string DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        public static string FOLLOWING_ERRORS_WERE_FOUND {
            get {
                return ResourceManager.GetString("FOLLOWING_ERRORS_WERE_FOUND", resourceCulture);
            }
        }
        
        public static string PHRASE_ALREADY_HAS_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_ALREADY_HAS_ACCOUNT", resourceCulture);
            }
        }
        
        public static string PHRASE_DO_LOGIN {
            get {
                return ResourceManager.GetString("PHRASE_DO_LOGIN", resourceCulture);
            }
        }
        
        public static string PHRASE_FORGOT_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("PHRASE_FORGOT_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        public static string PHRASE_CONTINUE_WITH_GOOGLE {
            get {
                return ResourceManager.GetString("PHRASE_CONTINUE_WITH_GOOGLE", resourceCulture);
            }
        }
        
        public static string PHRASE_DONT_HAVE_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_DONT_HAVE_ACCOUNT", resourceCulture);
            }
        }
        
        public static string PHRASE_PASSWORD_REQUIREMENTS {
            get {
                return ResourceManager.GetString("PHRASE_PASSWORD_REQUIREMENTS", resourceCulture);
            }
        }
        
        public static string PHRASE_LOGIN {
            get {
                return ResourceManager.GetString("PHRASE_LOGIN", resourceCulture);
            }
        }
        
        public static string PHRASE_REGISTER_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_REGISTER_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        public static string PHRASE_SMALL_TASKS_BIG_RESULTS {
            get {
                return ResourceManager.GetString("PHRASE_SMALL_TASKS_BIG_RESULTS", resourceCulture);
            }
        }
        
        public static string SERVER_COMMUNICATION_ERROR {
            get {
                return ResourceManager.GetString("SERVER_COMMUNICATION_ERROR", resourceCulture);
            }
        }
        
        public static string TITLE_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_EMAIL", resourceCulture);
            }
        }
        
        public static string TITLE_NAME {
            get {
                return ResourceManager.GetString("TITLE_NAME", resourceCulture);
            }
        }
        
        public static string TITLE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD", resourceCulture);
            }
        }
        
        public static string TITLE_REGISTER_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_MY_ACCOUNT", resourceCulture);
            }
        }
        
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
        
        public static string TRY_IT_AGAIN {
            get {
                return ResourceManager.GetString("TRY_IT_AGAIN", resourceCulture);
            }
        }
        
        public static string UPDATE_PROFILE {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE", resourceCulture);
            }
        }
    }
}
